cqt:
    fs:
    - 44100.  
    hop_length:
    - 512
    n_bins:
    - 80
    mono:
    - True
    bins_per_octave:
    - 12
    window:
    - 'hamming'
    
mel:
    fs:
    - 44100.  
    n_mels:
    - 64
    fmin:
    - 0.
    fmax:
    - 22050
    mono:
    - True
    hamming_window:
    - 1024.
    noverlap:
    - 0
    detrend:
    - False
    return_onesided:
    - True
    mode:
    - 'magnitude'

